import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/custom/header/header";
import Footer from "./components/custom/footer/footer";
import Sidebar from "./components/custom/sidebar/sidebar";
import Providers from "./provoider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          <div className="flex flex-col md:flex-row">
            <Sidebar/>
            {children}
          </div>       
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
